//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KpiLog
    {
        public int id { get; set; }
        public System.DateTime stamp { get; set; }
        public string Email { get; set; }
        public string Action { get; set; }
        public string Content { get; set; }
    }
}
